<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<table>
<tr><td><input onclick="ajaxFileUpload('/method1')" type="submit" value="method1"></td><td><input onclick="ajaxFileUpload('method2')" type="submit" value=""></td></tr>
</table>
<textarea style="width:600px; height: 100px">
</textarea>
<script type="text/javascript">
    function ajaxFileUpload(url) {
        $.ajax({
            url : url,
            type : 'POST',
            processData: false,  // tell jQuery not to process the data
            contentType: false,  // tell jQuery not to set contentType
            crossDomain: true,
            success : function(data) {
                $('textarea').val(data);
            },
            error: function(data) {
                $('textarea').val(data);
            },
        });
        return false;
    }
</script>